Fix Kotlin 2.2.21 compatibility: update IrClass.defaultType usage
The Kotlin IR API changed in version 2.2.21 where `IrClass.defaultType`
moved from `org.jetbrains.kotlin.ir.types` to `org.jetbrains.kotlin.ir.util`.

Additionally, `IrClassSymbol.defaultType` now requires accessing through
`.owner` to get the `IrClass.defaultType` extension.

This fixes the `NoSuchMethodError: IrTypesKt.getDefaultType` when using
Ktorfit with Kotlin 2.2.21.